Repository OPM/opm-common, pull requests merged in 2025-09, with the labels that each got.

#4708 Add support for binary input files in FileDeck and rst_deck
  examples/rst_deck.cpp
  opm/common/OpmLog/KeywordLocation.hpp
  opm/input/eclipse/Deck/DeckKeyword.cpp
  opm/input/eclipse/Deck/DeckKeyword.hpp
  opm/input/eclipse/Deck/DeckTree.cpp
  opm/input/eclipse/Deck/FileDeck.cpp
  opm/input/eclipse/Deck/FileDeck.hpp
  opm/input/eclipse/Deck/ImportContainer.cpp
Labels: manual:bugfix

#4712 Janitoring: Quell some static analyzer analytics
  opm/output/eclipse/WriteInit.cpp
  tests/parser/LgrOutputTests.cpp
  tests/test_AggregateWellDataLGR.cpp
Labels: manual:irrelevant

#4711 EclMaterialLawManager: put in namespace and rename
  examples/hysteresis.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
  tests/material/test_eclmateriallawmanager.cpp
  tests/material/test_hysteresis.cpp
Labels: manual:irrelevant

#4704 Ignore RxFT Summary Vectors for OOB Regions
  opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
  tests/parser/SummaryConfigTests.cpp
Labels: manual:bugfix

#4714 EclMaterialLawManager::InitParams::HystParams: rename EclMaterialLaw::HystParams
  CMakeLists_files.cmake
  opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.hpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
Labels: manual:irrelevant

#4716 EclMaterialLawManager::InitParams: rename EclMaterialLaw::InitParams
  CMakeLists_files.cmake
  opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.hpp
  opm/material/fluidmatrixinteractions/EclMaterialLawInitParams.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawInitParams.hpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
  opm/material/fluidmatrixinteractions/EclMaterialLawReadEffectiveParams.cpp
  opm/material/fluidmatrixinteractions/EclMaterialLawReadEffectiveParams.hpp
Labels: manual:irrelevant

#4685 Removing phase usage
  CMakeLists_files.cmake
  opm/material/fluidsystems/BlackOilDefaultFluidSystemIndices.hpp
  opm/material/fluidsystems/BlackOilFluidSystem.cpp
  opm/material/fluidsystems/BlackOilFluidSystem_macrotemplate.hpp
  opm/material/fluidsystems/PhaseUsageInfo.cpp
  opm/material/fluidsystems/PhaseUsageInfo.hpp
  tests/test_PhaseUsageInfo.cpp
Labels: manual:irrelevant

#4666 Reimplement support for Link Time Optimization
  cmake/Modules/OpmCompile.cmake
  cmake/Modules/OpmInterproceduralOptimization.cmake
  cmake/Modules/UseOptimization.cmake
  cmake/OPM-CMake.md
Labels: manual:irrelevant

#4502 Avoid excessive output from PyAction schedule.insert_keywords
  opm/input/eclipse/Parser/Parser.cpp
  opm/input/eclipse/Parser/Parser.hpp
  opm/input/eclipse/Schedule/Schedule.cpp
  python/cxx/schedule.cpp
Labels: manual:irrelevant

#4730 fixed: need to check for the full definition line
  cmake/Modules/FindHYPRE.cmake
Labels: manual:irrelevant

#4729 Add Restart Support for Satellite Production Rates
  opm/input/eclipse/Schedule/Group/Group.cpp
  opm/input/eclipse/Schedule/Schedule.cpp
  opm/io/eclipse/rst/group.cpp
  opm/io/eclipse/rst/group.hpp
  opm/output/eclipse/AggregateGroupData.cpp
  opm/output/eclipse/VectorItems/group.hpp
Labels: manual:irrelevant

#4724 Improve CO2STORE property evaluation performance
  opm/material/components/Brine.hpp
  opm/material/components/BrineDynamic.hpp
  opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
  opm/material/fluidsystems/blackoilpvt/BrineH2Pvt.hpp
Labels: manual:irrelevant

#4732 Fix python setup.py warnings
  python/CMakeLists.txt
  python/pyproject.toml
  python/setup.py.in
Labels: manual:irrelevant

#4737 Added include of cstdint
  opm/input/eclipse/Schedule/HandlerContext.hpp
Labels: manual:irrelevant

#4736 WSEGAICD item22
  opm/input/eclipse/Schedule/MSW/AICD.cpp
  opm/input/eclipse/Schedule/MSW/AICD.hpp
  opm/input/eclipse/share/keywords/000_Eclipse100/W/WSEGAICD
  opm/io/eclipse/rst/segment.hpp
  tests/parser/MultisegmentWellTests.cpp
Labels: manual:new-feature

#4507 Support WECON item 9
  opm/input/eclipse/Schedule/Events.hpp
  opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
  tests/parser/EventTests.cpp
Labels: manual:enhancement

#4744 this code in WELOPEN does not look useful.
  opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
Labels: manual:irrelevant

#4739 Prefer Initialisation List to Constructor Body
  opm/input/eclipse/Schedule/ScheduleTypes.cpp
Labels: manual:irrelevant

#4743 SALTSOL: change units of item 1 to Salinity (3)
  opm/input/eclipse/share/keywords/900_OPM/S/SALTSOL
Labels: manual:irrelevant

#4745 renaming PolymerDensity to PolymerConcentration and using Salinity for the third item in WPOLYMER
  opm/input/eclipse/Units/UnitSystem.cpp
  opm/input/eclipse/Units/Units.hpp
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYADS
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYADSS
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYMAX
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYSHLOG
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYVISC
  opm/input/eclipse/share/keywords/000_Eclipse100/W/WPOLYMER
  opm/input/eclipse/share/keywords/900_OPM/S/SKPRPOLY
  tests/parser/integration/ScheduleCreateFromDeck.cpp
Labels: manual:irrelevant

#4748 Communicate Connection Result's LGR Grid ID in Parallel
  opm/output/data/Wells.hpp
Labels: manual:irrelevant

#4749 merging three concentration units
  opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
  opm/input/eclipse/Units/UnitSystem.cpp
  opm/input/eclipse/Units/UnitSystem.hpp
  opm/input/eclipse/Units/Units.hpp
  opm/input/eclipse/share/keywords/000_Eclipse100/A/AQUCT
  opm/input/eclipse/share/keywords/000_Eclipse100/A/AQUFET
  opm/input/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
  opm/input/eclipse/share/keywords/000_Eclipse100/F/FOAMFSC
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYADS
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYADSS
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYMAX
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYSHLOG
  opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYVISC
  opm/input/eclipse/share/keywords/000_Eclipse100/S/SALT
  opm/input/eclipse/share/keywords/000_Eclipse100/S/SALTVD
  opm/input/eclipse/share/keywords/000_Eclipse100/S/SPOLY
  opm/input/eclipse/share/keywords/000_Eclipse100/W/WPOLYMER
  opm/input/eclipse/share/keywords/000_Eclipse100/W/WSALT
  opm/input/eclipse/share/keywords/900_OPM/S/SALTSOL
  opm/input/eclipse/share/keywords/900_OPM/S/SKPRPOLY
  opm/output/eclipse/Summary.cpp
  tests/parser/SaltTableTests.cpp
  tests/parser/integration/ScheduleCreateFromDeck.cpp
Labels: manual:irrelevant

#4740 Properly Restore Well's Preferred Phase on Restart
  CMakeLists_files.cmake
  opm/io/eclipse/rst/well.cpp
  opm/io/eclipse/rst/well.hpp
  tests/MODEL2_RESTART.DATA
  tests/parser/ScheduleTests.cpp
  tests/restart/MODEL2.UNRST
Labels: manual:bugfix

#4753 fix some doxy problems
  cmake/Templates/Doxyfile
  opm/material/components/Brine.hpp
  opm/material/components/BrineDynamic.hpp
Labels: manual:irrelevant

#4752 WECON keyword item 9: remove comment 'Not supported'
  opm/input/eclipse/share/keywords/000_Eclipse100/W/WECON
Labels: manual:irrelevant

#4757 Support UDQ Set/Scalar Operation for POW
  opm/input/eclipse/Schedule/UDQ/UDQFunction.cpp
  tests/parser/UDQTests.cpp
Labels: manual:enhancement

#4763 Add More Fracture and Filter Cake Summary Vectors
  opm/input/eclipse/share/keywords/900_OPM/C/CONNECTION_PROBE_OPM
  opm/output/data/Wells.hpp
  opm/output/eclipse/Summary.cpp
  tests/test_Summary.cpp
Labels: manual:irrelevant
