Repository OPM/opm-common, pull requests merged in 2025-06, with the labels that each got.

#4615 Add missing python documentation for opm-common
  python/README.md
  python/cxx/parser.cpp
  python/cxx/simulation_config.cpp
  python/cxx/table_manager.cpp
  python/cxx/unit_system.cpp
  python/cxx/well.cpp
  python/docstrings_common.json
  python/opm_embedded/__init__.pyi
Labels: manual:enhancement

#4624 changed: batch schedule iteration in runPyAction
  msim/src/msim.cpp
  opm/input/eclipse/Schedule/Action/SimulatorUpdate.hpp
  opm/input/eclipse/Schedule/Schedule.cpp
  opm/input/eclipse/Schedule/Schedule.hpp
  tests/msim/test_msim_ACTIONX.cpp
  tests/parser/ACTIONX.cpp
Labels: manual:enhancement

#4623 Varnish PvtxTable Implementation
  opm/input/eclipse/EclipseState/Tables/PvtxTable.cpp
  opm/input/eclipse/EclipseState/Tables/PvtxTable.hpp
Labels: manual:irrelevant

#4626 Remove Unused PvtxTable Member Function
  opm/input/eclipse/EclipseState/Tables/PvtxTable.cpp
  opm/input/eclipse/EclipseState/Tables/PvtxTable.hpp
  tests/parser/integration/ParseKEYWORD.cpp
Labels: manual:irrelevant

#4630 Varnish ScheduleStatic Implementation
  opm/input/eclipse/Schedule/ScheduleStatic.cpp
  opm/input/eclipse/Schedule/ScheduleStatic.hpp
Labels: manual:irrelevant

#4632 Don't Include <ranges> Header
  opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
  opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
Labels: manual:irrelevant

#4619 Diagnose Missing Wells/Groups in UDQ DEFINE Statements
  opm/input/eclipse/Parser/ParseContext.cpp
  opm/input/eclipse/Parser/ParseContext.hpp
  opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
  opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
  opm/input/eclipse/Schedule/UDQ/UDQKeywordHandlers.cpp
  tests/msim/test_msim_ACTIONX.cpp
  tests/parser/UDQTests.cpp
  tests/test_AggregateUDQData.cpp
  tests/test_AggregateWListData.cpp
Labels: manual:new-feature

#4636 update how to determine too high roughness
  opm/input/eclipse/Schedule/MSW/Segment.cpp
  opm/input/eclipse/Schedule/MSW/WellSegments.cpp
Labels: manual:irrelevant

#4638 Emit Usable Diagnostic for Unuspported Restart Report Number
  opm/input/eclipse/EclipseState/InitConfig/InitConfig.cpp
  tests/parser/InitConfigTest.cpp
Labels: manual:enhancement

#4609 refactoring GroupLimitAction, adding exceed action for oil for GCONPROD keyword
  opm/input/eclipse/Schedule/Group/Group.cpp
  opm/input/eclipse/Schedule/Group/Group.hpp
  opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp
Labels: manual:irrelevant

#4640 removing the test related to deleted spe9/SPE9_CP_GROUP.DATA
  ExtraTests.cmake
Labels: manual:irrelevant

#4635 Interpret GCONPROD FLD controls as inheriting control from parent(s).
  opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp
Labels: manual:bugfix

#4639 returning zero guide rate instead of throw due to invalid denominator.
  opm/input/eclipse/Schedule/Group/GuideRate.cpp
  opm/input/eclipse/Schedule/Group/GuideRate.hpp
  opm/input/eclipse/Schedule/Group/GuideRateModel.cpp
  opm/input/eclipse/Schedule/Group/GuideRateModel.hpp
  tests/parser/GroupTests.cpp
Labels: manual:irrelevant

#4646 Document Internal EclipseIO::Impl Class
  opm/output/eclipse/EclipseIO.cpp
  opm/output/eclipse/EclipseIO.hpp
Labels: manual:irrelevant

#4650 Remove unused capillary pressure storage.
  opm/material/fluidstates/BlackOilFluidState.hpp
Labels: manual:enhancement

#4651 Remove conversions and accessors for empty ConditionalStorage.
  opm/material/checkFluidSystem.hpp
  opm/material/common/ConditionalStorage.hpp
  tests/test_ConditionalStorage.cpp
Labels: manual:enhancement
