Repository OPM/opm-common, pull requests merged in 2025-05, with the labels that each got.

#4606 add github action for checking manual labels
  .github/workflows/manual_label_checker.yml
Labels: manual:irrelevant

#4439 Output More Restart File Items
  opm/input/eclipse/Schedule/UDQ/UDQActive.cpp
  opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp
  opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
  opm/input/eclipse/Units/UnitSystem.cpp
  opm/io/eclipse/rst/connection.cpp
  opm/io/eclipse/rst/state.cpp
  opm/io/eclipse/rst/state.hpp
  opm/io/eclipse/rst/udq.cpp
  opm/io/eclipse/rst/udq.hpp
  opm/output/eclipse/AggregateConnectionData.cpp
  opm/output/eclipse/AggregateUDQData.cpp
  opm/output/eclipse/CreateInteHead.cpp
  opm/output/eclipse/InteHEAD.cpp
  opm/output/eclipse/VectorItems/connection.hpp
  opm/output/eclipse/VectorItems/udq.hpp
  tests/parser/UDQTests.cpp
  tests/test_AggregateConnectionData.cpp
Labels: manual:new-feature

#4604 Throw if two processes try to write different output data for the same well, warn if they try to write the same
  opm/output/data/Wells.hpp
Labels: manual:irrelevant

#4503 Support UDA and restart for RESV control in GCONPROD
  opm/input/eclipse/Schedule/Group/Group.cpp
  opm/input/eclipse/Schedule/Group/Group.hpp
  opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp
  opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp
  opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
  opm/input/eclipse/Units/UnitSystem.cpp
  opm/input/eclipse/share/keywords/000_Eclipse100/G/GCONPROD
  opm/io/eclipse/rst/group.cpp
  opm/io/eclipse/rst/group.hpp
  opm/output/eclipse/AggregateGroupData.cpp
  opm/output/eclipse/VectorItems/group.hpp
Labels: manual:enhancement

#4607 Ignoring TNavigator spesific arrays in summary file
  opm/io/eclipse/ESmry.cpp
  opm/io/eclipse/ESmry.hpp
Labels: manual:irrelevant

#4613 Don't Log Errors Immediately for DELAYED_EXIT1
  opm/input/eclipse/Parser/ParseContext.cpp
Labels: manual:bugfix

#4610 Add missing python documentation
  python/cxx/eclipse_io.cpp
  python/cxx/emodel_util.cpp
  python/cxx/field_props.cpp
  python/cxx/log.cpp
  python/docstrings_common.json
  python/opm/_common.py
  python/opm/util/__init__.py
Labels: manual:irrelevant

#4612 Support Identifying Requisite UDQ Schedule Objects
  opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
  opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
  opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
  opm/input/eclipse/Schedule/UDQ/UDQDefine.hpp
  opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
  tests/parser/UDQTests.cpp
Labels: manual:irrelevant

#4620 Remove some unused buildsystem files
  cmake/Modules/Findopm-verteq.cmake
  cmake/Modules/OpmPythonTest.cmake
  cmake/Templates/la.in
  cmake/Templates/opm-project.pc.in
Labels: manual:irrelevant

#4616 Reduce Cost of WListManager::wells()
  opm/input/eclipse/Schedule/Well/WListManager.cpp
Labels: manual:irrelevant

#4617 Tidy Up WListManager::newList Implementation
  opm/input/eclipse/Schedule/Well/WList.cpp
  opm/input/eclipse/Schedule/Well/WList.hpp
  opm/input/eclipse/Schedule/Well/WListManager.cpp
  opm/input/eclipse/Schedule/Well/WListManager.hpp
Labels: manual:irrelevant

#4618 Add Well/Group Existence Predicates to HandlerContext
  opm/input/eclipse/Schedule/HandlerContext.cpp
  opm/input/eclipse/Schedule/HandlerContext.hpp
  opm/input/eclipse/Schedule/Well/NameOrder.cpp
  opm/input/eclipse/Schedule/Well/NameOrder.hpp
  opm/input/eclipse/Schedule/Well/WList.hpp
  opm/input/eclipse/Schedule/Well/WListManager.cpp
  opm/input/eclipse/Schedule/Well/WListManager.hpp
  opm/input/eclipse/Schedule/Well/WellMatcher.cpp
  opm/input/eclipse/Schedule/Well/WellMatcher.hpp
  tests/parser/ScheduleTests.cpp
Labels: manual:irrelevant

#4590 Swithching constructor argument order for Segment to be depth and then length
  opm/input/eclipse/Schedule/MSW/Segment.cpp
  opm/input/eclipse/Schedule/MSW/Segment.hpp
  opm/input/eclipse/Schedule/MSW/WellSegments.cpp
  opm/input/eclipse/Schedule/MSW/WellSegments.hpp
  tests/parser/UDQTests.cpp
  tests/test_SegmentMatcher.cpp
Labels: manual:irrelevant
